name: Rust

on:
  push:
    branches: [ "pages" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install wasm-pack
      uses: baptiste0928/cargo-install@v1
      with:
        crate: wasm-pack
        version: "0.10"
    - name: Install rust version
      working-directory: ./web
      run: rustup show
    - name: Cache rust deps
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: web
    - name: Build wdht-web
      working-directory: ./web
      run: make pkg-web
    - uses: actions/setup-node@v3
      with:
        node-version: 17
    - run: yarn
      working-directory: ./example_chat
    - name: Build site
      working-directory: ./example_chat
      run: yarn build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./example_chat/dist
