name: Rust

on:
  push:
    branches: [ "pages" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build wdht-web
      working-directory: ./web
      run: make pkg-web
    - uses: actions/setup-node@v3
      with:
        node-version: 17
    - run: yarn
    - name: Build site
      working-directory: ./example_chat
      run: yarn build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./example_chat/dist
        
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
